// React Query önbellek anahtarları — tek yerde, böylece bir kayıttan sonra hangi listelerin yenileneceği buradan okunur.
// Kural: anahtar(filtre) → ["kaynak", filtre]; anahtar() → ["kaynak"] tüm filtreleri kapsar (invalidate için).
export const anahtar = {
  oturum: ["oturum"],
  bekleyenler: ["panel", "bekleyenler"],
  panelOzet: (donem) => ["panel", "ozet", donem],
  haftalikHacim: ["panel", "haftalik-hacim"],
  bakiye: ["panel", "bakiye"],
  islemler: (filtre) => (filtre ? ["islemler", filtre] : ["islemler"]),
  musteriler: (filtre) => (filtre ? ["musteriler", filtre] : ["musteriler"]),
  tahsilatCarileri: ["tahsilat-carileri"],
  firma: ["firma"],
  ortaklar: ["firma", "ortaklar"],
  taksitSecenekleri: (girdi) => (girdi ? ["odeme", "taksit-secenekleri", girdi] : ["odeme", "taksit-secenekleri"]),
  odemeLinkleri: (filtre) => (filtre ? ["odeme-linkleri", filtre] : ["odeme-linkleri"]),
  talepler: (filtre) => (filtre ? ["iptal-iade-talepleri", filtre] : ["iptal-iade-talepleri"]),
  talepUygunIslemler: ["iptal-iade-talepleri", "uygun-islemler"],
  bayiler: (filtre) => (filtre ? ["bayiler", filtre] : ["bayiler"]),
  bayi: (cariNo) => ["bayiler", "tek", cariNo],
  altBayiler: ["alt-bayiler"],
  faturalar: (filtre) => (filtre ? ["faturalar", filtre] : ["faturalar"]),
  bayiOzeti: (filtre) => (filtre ? ["raporlar", "bayi-ozet", filtre] : ["raporlar", "bayi-ozet"]),
  bayiFaturaOzeti: (filtre) => (filtre ? ["raporlar", "bayi-fatura-ozet", filtre] : ["raporlar", "bayi-fatura-ozet"]),
  vadeFarkiProfilleri: ["vade-farki-profilleri"],
  kullanicilar: (filtre) => (filtre ? ["kullanicilar", filtre] : ["kullanicilar"]),
  uyeIsyerleri: ["uye-isyerleri"],
};
