// React Query önbellek anahtarları — tek yerde, böylece bir kayıttan sonra hangi listelerin yenileneceği buradan okunur.
// Kural: anahtar(filtre) → ["kaynak", filtre]; anahtar() → ["kaynak"] tüm filtreleri kapsar (invalidate için).
export const queryKeys = {
  session: ["oturum"],
  pendingItems: ["panel", "bekleyenler"],
  panelSummary: (period) => ["panel", "ozet", period],
  weeklyVolume: ["panel", "haftalik-hacim"],
  balance: ["panel", "bakiye"],
  transactions: (filter) => (filter ? ["islemler", filter] : ["islemler"]),
  customers: (filter) => (filter ? ["musteriler", filter] : ["musteriler"]),
  collectionAccounts: ["tahsilat-carileri"],
  company: ["firma"],
  partners: ["firma", "ortaklar"],
  installmentOptions: (input) => (input ? ["odeme", "taksit-secenekleri", input] : ["odeme", "taksit-secenekleri"]),
  paymentLinks: (filter) => (filter ? ["odeme-linkleri", filter] : ["odeme-linkleri"]),
  requests: (filter) => (filter ? ["iptal-iade-talepleri", filter] : ["iptal-iade-talepleri"]),
  eligibleTransactions: ["iptal-iade-talepleri", "uygun-islemler"],
  dealers: (filter) => (filter ? ["bayiler", filter] : ["bayiler"]),
  dealer: (accountNo) => ["bayiler", "tek", accountNo],
  subDealers: ["alt-bayiler"],
  invoices: (filter) => (filter ? ["faturalar", filter] : ["faturalar"]),
  dealerSummary: (filter) => (filter ? ["raporlar", "bayi-ozet", filter] : ["raporlar", "bayi-ozet"]),
  dealerInvoiceSummary: (filter) => (filter ? ["raporlar", "bayi-fatura-ozet", filter] : ["raporlar", "bayi-fatura-ozet"]),
  maturityProfiles: ["vade-farki-profilleri"],
  rates: ["kurlar"],
  announcements: ["duyurular"],
  balanceStatement: (filter) => (filter ? ["bakiye", "ekstre", filter] : ["bakiye", "ekstre"]),
  users: (filter) => (filter ? ["kullanicilar", filter] : ["kullanicilar"]),
  merchants: ["uye-isyerleri"],
};
